"""Creando columna uuid2

Revision ID: 4b605d83ed62
Revises: 861801d4cfc5
Create Date: 2024-01-09 13:05:45.231018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b605d83ed62'
down_revision: Union[str, None] = '861801d4cfc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('uuid2', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'uuid2')
    # ### end Alembic commands ###
