"""Eliminando columna fullname2

Revision ID: 4e7a0c78436e
Revises: 89bfc98dab39
Create Date: 2024-01-09 13:20:47.744479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e7a0c78436e'
down_revision: Union[str, None] = '89bfc98dab39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'full_name2')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('full_name2', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
