"""Crear modelos2

Revision ID: 861801d4cfc5
Revises: 
Create Date: 2024-01-09 12:59:02.503040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '861801d4cfc5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('cover_photo', sa.LargeBinary(), nullable=True),
    sa.Column('profile_picture', sa.LargeBinary(), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('cv', sa.LargeBinary(), nullable=True),
    sa.Column('images_certificates_titles', sa.ARRAY(sa.LargeBinary()), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('years_experiences', sa.Integer(), nullable=True),
    sa.Column('profession_or_title', sa.String(length=30), nullable=True),
    sa.Column('languages', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('links_social_networks', sa.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profile')
    op.drop_table('user')
    # ### end Alembic commands ###
