"""Otra Eliminando columna uuid2

Revision ID: f801f3453769
Revises: 8ccf95bba083
Create Date: 2024-01-09 13:13:14.607315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f801f3453769'
down_revision: Union[str, None] = '8ccf95bba083'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'uuid2')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('uuid2', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
